// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq
package http_test

import (
	"context"
	"sync"

	"github.com/andreasstove999/ecommerce-system/cart-service-go/internal/cart"
)

// RepositoryMock is a mock implementation of cart.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//	    // make and configure a mocked cart.Repository
//	    mockedRepository := &RepositoryMock{
//	        GetCartFunc: func(ctx context.Context, userID string) (*cart.Cart, error) {
//	            panic("mock out the GetCart method")
//	        },
//	        UpsertCartFunc: func(ctx context.Context, c *cart.Cart) error {
//	            panic("mock out the UpsertCart method")
//	        },
//	        ClearCartFunc: func(ctx context.Context, userID string) error {
//	            panic("mock out the ClearCart method")
//	        },
//	    }
//
//	    // use mockedRepository in code that requires cart.Repository
//	}
type RepositoryMock struct {
	// GetCartFunc mocks the GetCart method.
	GetCartFunc func(ctx context.Context, userID string) (*cart.Cart, error)

	// UpsertCartFunc mocks the UpsertCart method.
	UpsertCartFunc func(ctx context.Context, c *cart.Cart) error

	// ClearCartFunc mocks the ClearCart method.
	ClearCartFunc func(ctx context.Context, userID string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetCart holds details about calls to the GetCart method.
		GetCart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// UpsertCart holds details about calls to the UpsertCart method.
		UpsertCart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C *cart.Cart
		}
		// ClearCart holds details about calls to the ClearCart method.
		ClearCart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockRepositoryMockGetCart    sync.RWMutex
	lockRepositoryMockUpsertCart sync.RWMutex
	lockRepositoryMockClearCart  sync.RWMutex
}

// GetCart calls GetCartFunc.
func (mock *RepositoryMock) GetCart(ctx context.Context, userID string) (*cart.Cart, error) {
	if mock.GetCartFunc == nil {
		panic("RepositoryMock.GetCartFunc: method is nil but Repository.GetCart was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{Ctx: ctx, UserID: userID}
	mock.lockRepositoryMockGetCart.Lock()
	mock.calls.GetCart = append(mock.calls.GetCart, callInfo)
	mock.lockRepositoryMockGetCart.Unlock()
	return mock.GetCartFunc(ctx, userID)
}

// GetCartCalls gets all the calls that were made to GetCart.
// Check the length with:
//
//	len(mockedRepository.GetCartCalls())
func (mock *RepositoryMock) GetCartCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockRepositoryMockGetCart.RLock()
	calls = mock.calls.GetCart
	mock.lockRepositoryMockGetCart.RUnlock()
	return calls
}

// UpsertCart calls UpsertCartFunc.
func (mock *RepositoryMock) UpsertCart(ctx context.Context, c *cart.Cart) error {
	if mock.UpsertCartFunc == nil {
		panic("RepositoryMock.UpsertCartFunc: method is nil but Repository.UpsertCart was just called")
	}
	callInfo := struct {
		Ctx context.Context
		C   *cart.Cart
	}{Ctx: ctx, C: c}
	mock.lockRepositoryMockUpsertCart.Lock()
	mock.calls.UpsertCart = append(mock.calls.UpsertCart, callInfo)
	mock.lockRepositoryMockUpsertCart.Unlock()
	return mock.UpsertCartFunc(ctx, c)
}

// UpsertCartCalls gets all the calls that were made to UpsertCart.
// Check the length with:
//
//	len(mockedRepository.UpsertCartCalls())
func (mock *RepositoryMock) UpsertCartCalls() []struct {
	Ctx context.Context
	C   *cart.Cart
} {
	var calls []struct {
		Ctx context.Context
		C   *cart.Cart
	}
	mock.lockRepositoryMockUpsertCart.RLock()
	calls = mock.calls.UpsertCart
	mock.lockRepositoryMockUpsertCart.RUnlock()
	return calls
}

// ClearCart calls ClearCartFunc.
func (mock *RepositoryMock) ClearCart(ctx context.Context, userID string) error {
	if mock.ClearCartFunc == nil {
		panic("RepositoryMock.ClearCartFunc: method is nil but Repository.ClearCart was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{Ctx: ctx, UserID: userID}
	mock.lockRepositoryMockClearCart.Lock()
	mock.calls.ClearCart = append(mock.calls.ClearCart, callInfo)
	mock.lockRepositoryMockClearCart.Unlock()
	return mock.ClearCartFunc(ctx, userID)
}

// ClearCartCalls gets all the calls that were made to ClearCart.
// Check the length with:
//
//	len(mockedRepository.ClearCartCalls())
func (mock *RepositoryMock) ClearCartCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockRepositoryMockClearCart.RLock()
	calls = mock.calls.ClearCart
	mock.lockRepositoryMockClearCart.RUnlock()
	return calls
}
